### ISSUE TITLE
Improvement Suggestions

### ISSUE THREAD

**Issue by otsfan203** [N-language/N-language.github.io#5]
**1. Site Address** I recommend changing the title to N-language.github.io to make a shorter domain, so that N# is more accessible. Small things like this can make a big difference.

**2. Favicons** I know the N# logo is undecided, but can I set a temporary favicon so that the site isn't located at a page with no favicon?  Websites look much better, professional, and reliable if they have favicons, even if they're only temporary. And obviously, we can change the favicon when an official logo is decided on.

REF: #6 (Temporary Favicon)

**Comment by otsfan203** [comment]
I'll create a pull request for the favicon. If you want a different temporary one, tell me.

**Comment by BonfireScratch** [comment]
I am aware of the first issue. However, I have no idea how to fix it. As for the second one, I totally agree.

**Comment by otsfan203** [comment]
@BonfireScratch You already merged my pull request for the first one, so that's done, and all you have to do for the shorter domain is change the name of N-language/WebClient to N-language/N-language.github.io

**Comment by BonfireScratch** [comment]
@otsfan203 erm... How?

**Comment by otsfan203** [comment]
@BonfireScratch Go to Settings and change the name to N-language.github.io

**Comment by BonfireScratch** [comment]
@otsfan203 OK! :+1:

**Comment by BonfireScratch** [comment]
@otsfan203 should we create a redirectory if people lose track of the website's URL?

**Comment by otsfan203** [comment]
@BonfireScratch Sure!

**Comment by otsfan203** [comment]
@BonfireScratch  Done :)
